/**
 * Sibiu Geo Brain — Zone Database
 * Source: OpenStreetMap + local knowledge
 * Coordonate verificate OSM 2024
 */

const SIBIU_ZONES = [
    {
        id: 'centru',
        name: 'Centrul Istoric',
        city: 'Sibiu',
        lat: 45.797,
        lng: 24.1499,
        radius_km: 1.0,
        aliases: [
            'centru', 'centrul', 'centru istoric', 'centrul istoric',
            'piata mare', 'piața mare', 'piata mica', 'piața mică',
            'piata unirii', 'piața unirii', 'centrul civic',
            'city center', 'old town', 'oras vechi', 'orașul vechi'
        ],
        tags: ['historic', 'tourist', 'expensive', 'walking', 'restaurants', 'culture', 'premium'],
        nearby_areas: ['oras_de_jos', 'oras_de_sus', 'terezian'],
        poi: ['Piața Mare', 'Piața Mică', 'Podul Minciunilor', 'Turnul Sfatului', 'Catedrala Evanghelică'],
        price_index: 1.4,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'high',
        parking: 'difficult',
    },
    {
        id: 'oras_de_jos',
        name: 'Orașul de Jos',
        city: 'Sibiu',
        lat: 45.7996,
        lng: 24.1481,
        radius_km: 1.2,
        aliases: [
            'orasul de jos', 'orașul de jos', 'jos', 'sub cetate', 'sub cetate',
            'centrul civic', 'centru civic'
        ],
        tags: ['central', 'residential', 'historic', 'mid_price'],
        nearby_areas: ['centru', 'oras_de_sus', 'terezian', 'lazaret'],
        poi: ['Parcul Sub Arini', 'Spitalul Județean', 'Liceul Gheorghe Lazăr'],
        price_index: 1.2,
        student_friendly: true,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'medium',
    },
    {
        id: 'oras_de_sus',
        name: 'Orașul de Sus',
        city: 'Sibiu',
        lat: 45.7958,
        lng: 24.153,
        radius_km: 1.0,
        aliases: [
            'orasul de sus', 'orașul de sus', 'sus', 'deasupra', 'cetate'
        ],
        tags: ['central', 'historic', 'expensive', 'quiet'],
        nearby_areas: ['centru', 'oras_de_jos', 'terezian'],
        poi: ['Bastionul Haller', 'Grădina Publică'],
        price_index: 1.3,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'low',
        parking: 'medium',
    },
    {
        id: 'hipodrom',
        name: 'Hipodrom',
        city: 'Sibiu',
        lat: 45.7785,
        lng: 24.152,
        radius_km: 1.8,
        aliases: [
            'hipodrom', 'hipodrom 1', 'hipodrom 2', 'hipodrom 3', 'hipodrom 4',
            'hipodrom i', 'hipodrom ii', 'hipodrom iii', 'hipodrom iv',
            'hipo', 'zona hipodrom'
        ],
        tags: ['family', 'blocks', 'schools', 'mid_price', 'good_transport', 'park'],
        nearby_areas: ['vale_aurie', 'dumbrăvii', 'centru'],
        poi: ['Parcul Hipodrom', 'Liceul Onisifor Ghibu', 'Shopping City (aproape)'],
        price_index: 1.0,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'good',
    },
    {
        id: 'vale_aurie',
        name: 'Valea Aurie',
        city: 'Sibiu',
        lat: 45.7704,
        lng: 24.1263,
        radius_km: 1.5,
        aliases: [
            'valea aurie', 'vale aurie', 'valcea', 'val auriu'
        ],
        tags: ['residential', 'quiet', 'affordable', 'nature', 'blocks'],
        nearby_areas: ['hipodrom', 'strand', 'tilisca'],
        poi: ['Parcul Valea Aurie'],
        price_index: 0.85,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'low',
        parking: 'good',
    },
    {
        id: 'strand',
        name: 'Ștrand',
        city: 'Sibiu',
        lat: 45.785,
        lng: 24.133,
        radius_km: 1.2,
        aliases: [
            'strand', 'ștrand', 'strand 1', 'strand 2', 'strand ii',
            'zona strand', 'langa strand'
        ],
        tags: ['residential', 'affordable', 'blocks', 'transport'],
        nearby_areas: ['hipodrom', 'vale_aurie', 'turnisor'],
        poi: ['Ștrandul Municipal Sibiu'],
        price_index: 0.9,
        student_friendly: true,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'good',
    },
    {
        id: 'turnisor',
        name: 'Turnișor',
        city: 'Sibiu',
        lat: 45.7912,
        lng: 24.1187,
        radius_km: 1.5,
        aliases: [
            'turnisor', 'turnișor', 'turnishor', 'zona turnisor',
            'langa promenada', 'promenada', 'promenada sibiu'
        ],
        tags: ['residential', 'commercial', 'promenada', 'shopping', 'mid_price', 'transport'],
        nearby_areas: ['strand', 'vest', 'nord_vest'],
        poi: ['Promenada Sibiu', 'Kaufland Turnisor', 'Lidl Turnisor'],
        price_index: 1.05,
        student_friendly: true,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'good',
    },
    {
        id: 'terezian',
        name: 'Terezian',
        city: 'Sibiu',
        lat: 45.8064,
        lng: 24.1443,
        radius_km: 1.0,
        aliases: [
            'terezian', 'terezianum', 'zona terezian'
        ],
        tags: ['quiet', 'residential', 'premium', 'houses', 'garden'],
        nearby_areas: ['centru', 'oras_de_jos', 'nord_vest'],
        poi: ['Piața Teatrului', 'Teatrul Național Sibiu'],
        price_index: 1.15,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'low',
        parking: 'good',
    },
    {
        id: 'vasile_aaron',
        name: 'Vasile Aaron',
        city: 'Sibiu',
        lat: 45.785,
        lng: 24.172,
        radius_km: 1.2,
        aliases: [
            'vasile aaron', 'aaron', 'zona aaron', 'trei stejari',
            'langa ulbs', 'campus', 'universitate'
        ],
        tags: ['student', 'university', 'affordable', 'transport', 'ULBS'],
        nearby_areas: ['lazaret', 'gusterita', 'centru'],
        poi: ['ULBS - Facultatea de Drept', 'Căminele ULBS', 'Campus Universitar'],
        price_index: 0.95,
        student_friendly: true,
        family_friendly: false,
        noise_level: 'medium',
        parking: 'medium',
    },
    {
        id: 'lazaret',
        name: 'Lazaret',
        city: 'Sibiu',
        lat: 45.802,
        lng: 24.1726,
        radius_km: 1.0,
        aliases: [
            'lazaret', 'lazăret', 'zona lazaret'
        ],
        tags: ['residential', 'quiet', 'mid_price', 'houses'],
        nearby_areas: ['vasile_aaron', 'gusterita', 'oras_de_jos'],
        poi: ['Spitalul de Pneumoftiziologie', 'Parcul Lazaret'],
        price_index: 1.0,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'low',
        parking: 'good',
    },
    {
        id: 'gusterita',
        name: 'Gușterița',
        city: 'Sibiu',
        lat: 45.8112,
        lng: 24.1834,
        radius_km: 1.5,
        aliases: [
            'gusterita', 'gușterița', 'gusterița', 'zona gusterita'
        ],
        tags: ['residential', 'affordable', 'houses', 'quiet', 'outskirts'],
        nearby_areas: ['vasile_aaron', 'lazaret', 'cfr'],
        poi: ['Industria Bumbacului'],
        price_index: 0.8,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'low',
        parking: 'good',
    },
    {
        id: 'nord_vest',
        name: 'Nord-Vest',
        city: 'Sibiu',
        lat: 45.8087,
        lng: 24.1124,
        radius_km: 1.5,
        aliases: [
            'nord vest', 'nord-vest', 'zona nord', 'nord sibiu',
            'langa aeroport', 'aeroport sibiu', 'zona aeroport'
        ],
        tags: ['residential', 'affordable', 'houses', 'airport_proximity'],
        nearby_areas: ['turnisor', 'terezian', 'tineretului'],
        poi: ['Aeroportul Internațional Sibiu', 'Parc Industrial'],
        price_index: 0.85,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'good',
    },
    {
        id: 'tineretului',
        name: 'Tineretului',
        city: 'Sibiu',
        lat: 45.8163,
        lng: 24.1316,
        radius_km: 1.2,
        aliases: [
            'tineretului', 'zona tineretului', 'cartier tineret'
        ],
        tags: ['residential', 'blocks', 'affordable', 'transport'],
        nearby_areas: ['nord_vest', 'terezian', 'veteranilor'],
        poi: ['Stadionul Municipal'],
        price_index: 0.9,
        student_friendly: true,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'medium',
    },
    {
        id: 'shopping_city_zone',
        name: 'Zona Shopping City',
        city: 'Sibiu',
        lat: 45.773,
        lng: 24.144,
        radius_km: 1.5,
        aliases: [
            'shopping city', 'shopping city sibiu', 'langa shopping city',
            'zona mall', 'mall', 'langa mall'
        ],
        tags: ['commercial', 'shopping', 'transport', 'blocks', 'affordable'],
        nearby_areas: ['hipodrom', 'vale_aurie', 'dumbrăvii'],
        poi: ['Shopping City Sibiu', 'Kaufland', 'Cinema City', 'IKEA (aproape)'],
        price_index: 0.95,
        student_friendly: true,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'excellent',
    },
    {
        id: 'dumbravii',
        name: 'Dumbravii',
        city: 'Sibiu',
        lat: 45.7774,
        lng: 24.1432,
        radius_km: 1.2,
        aliases: [
            'dumbravii', 'dumbrăvii', 'zona dumbravii', 'dumbrava'
        ],
        tags: ['residential', 'quiet', 'nature', 'houses', 'affordable'],
        nearby_areas: ['hipodrom', 'vale_aurie', 'shopping_city_zone'],
        poi: ['Dumbrava Sibiului', 'Muzeul ASTRA', 'Grădina Zoologică'],
        price_index: 0.9,
        student_friendly: false,
        family_friendly: true,
        noise_level: 'low',
        parking: 'excellent',
    },
    {
        id: 'sibiu_general',
        name: 'Sibiu',
        city: 'Sibiu',
        lat: 45.7973,
        lng: 24.1519,
        radius_km: 10.0,
        aliases: ['sibiu', 'tot sibiuul', 'orice zona', 'oriunde in sibiu'],
        tags: ['general'],
        nearby_areas: [],
        poi: [],
        price_index: 1.0,
        student_friendly: true,
        family_friendly: true,
        noise_level: 'medium',
        parking: 'medium',
    },
];

// POI database — points of interest cu coordonate exacte
const SIBIU_POIS = {
    'promenada': { name: 'Promenada Sibiu', lat: 45.7895, lng: 24.1172, area_id: 'turnisor', radius_km: 2.0 },
    'shopping city': { name: 'Shopping City Sibiu', lat: 45.773, lng: 24.144, area_id: 'shopping_city_zone', radius_km: 2.0 },
    'mall': { name: 'Shopping City Sibiu', lat: 45.773, lng: 24.144, area_id: 'shopping_city_zone', radius_km: 2.0 },
    'ulbs': { name: 'ULBS - Universitatea Lucian Blaga', lat: 45.785, lng: 24.172, area_id: 'vasile_aaron', radius_km: 1.5 },
    'universitate': { name: 'ULBS', lat: 45.785, lng: 24.172, area_id: 'vasile_aaron', radius_km: 1.5 },
    'facultate': { name: 'ULBS', lat: 45.785, lng: 24.172, area_id: 'vasile_aaron', radius_km: 1.5 },
    'campus': { name: 'Campus ULBS', lat: 45.785, lng: 24.172, area_id: 'vasile_aaron', radius_km: 1.5 },
    'aeroport': { name: 'Aeroportul Internațional Sibiu', lat: 45.8156, lng: 24.0913, area_id: 'nord_vest', radius_km: 3.0 },
    'gara': { name: 'Gara Sibiu', lat: 45.8039, lng: 24.1496, area_id: 'terezian', radius_km: 1.5 },
    'spital': { name: 'Spitalul Județean Sibiu', lat: 45.7996, lng: 24.148, area_id: 'oras_de_jos', radius_km: 1.0 },
    'spital judetean': { name: 'Spitalul Județean Sibiu', lat: 45.7996, lng: 24.148, area_id: 'oras_de_jos', radius_km: 1.0 },
    'piata mare': { name: 'Piața Mare', lat: 45.7974, lng: 24.1518, area_id: 'centru', radius_km: 0.5 },
    'piata mica': { name: 'Piața Mică', lat: 45.7969, lng: 24.151, area_id: 'centru', radius_km: 0.5 },
    'podul minciunilor': { name: 'Podul Minciunilor', lat: 45.7966, lng: 24.1503, area_id: 'centru', radius_km: 0.5 },
    'dumbrava': { name: 'Dumbrava Sibiului', lat: 45.76, lng: 24.14, area_id: 'dumbravii', radius_km: 2.0 },
    'muzeu astra': { name: 'Muzeul ASTRA', lat: 45.757, lng: 24.139, area_id: 'dumbravii', radius_km: 2.0 },
    'parcul sub arini': { name: 'Parcul Sub Arini', lat: 45.799, lng: 24.148, area_id: 'oras_de_jos', radius_km: 1.0 },
    'teatrul national': { name: 'Teatrul Național Sibiu', lat: 45.8001, lng: 24.146, area_id: 'terezian', radius_km: 1.0 },
    'teatru': { name: 'Teatrul Național Sibiu', lat: 45.8001, lng: 24.146, area_id: 'terezian', radius_km: 1.0 },
    'kaufland': { name: 'Kaufland Sibiu', lat: 45.783, lng: 24.119, area_id: 'turnisor', radius_km: 1.5 },
};

// Semantic lifestyle tags → zone IDs
const LIFESTYLE_MAP = {
    student: ['vasile_aaron', 'strand', 'tineretului', 'hipodrom'],
    familie: ['hipodrom', 'dumbravii', 'lazaret', 'terezian', 'turnisor'],
    pensionar: ['centru', 'oras_de_jos', 'terezian', 'dumbravii'],
    linistit: ['dumbravii', 'vale_aurie', 'gusterita', 'lazaret', 'terezian'],
    'central': ['centru', 'oras_de_jos', 'oras_de_sus'],
    ieftin: ['gusterita', 'vale_aurie', 'nord_vest', 'strand', 'tineretului'],
    scump: ['centru', 'oras_de_sus', 'terezian'],
    premium: ['centru', 'oras_de_sus', 'terezian'],
    investitie: ['centru', 'turnisor', 'hipodrom', 'shopping_city_zone'],
    transport: ['strand', 'tineretului', 'hipodrom', 'vasile_aaron'],
    nature: ['dumbravii', 'vale_aurie', 'gusterita'],
    historic: ['centru', 'oras_de_jos', 'oras_de_sus'],
};

module.exports = { SIBIU_ZONES, SIBIU_POIS, LIFESTYLE_MAP };
